### ISSUE TITLE
docker pid is not same as nvml pid

### ISSUE THREAD

**Issue by Lzhang-hub** [lxyzhangqing/gpu-memory-monitor#1]
I find the pid get through docker inspect is not same as nvml pid; it is pid and ppid relation.
![image](https://user-images.githubusercontent.com/57925599/168268948-74d8ac71-91ba-44f1-a686-ec68a24bb76c.png)

**Comment by lxyzhangqing** [comment]
@Lzhang-hub I suggest you run your python program directly, like this `docker run python:latest python xxxx`
